// <auto-generated />
using System;
using AtmMachine.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AtmMachine.Migrations
{
    [DbContext(typeof(AtmContext))]
    [Migration("20181103193324_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AtmMachine.Entities.GiftCardDetails", b =>
                {
                    b.Property<Guid>("GiftCardId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<string>("CardNumber");

                    b.HasKey("GiftCardId");

                    b.ToTable("GiftCardDetails");

                    b.HasData(
                        new { GiftCardId = new Guid("e652001d-8d64-4118-ac58-62b90a93c4da"), Amount = 50, CardNumber = "6104337968574416" },
                        new { GiftCardId = new Guid("52ca9ed2-a192-4d5f-bebf-4b9d5c879436"), Amount = 150, CardNumber = "6104337968575519" },
                        new { GiftCardId = new Guid("ca13a3d2-4fd9-4d8a-8789-6ef8c9f8bfb4"), Amount = 250, CardNumber = "6104337968576728" },
                        new { GiftCardId = new Guid("fc64e1f4-65b7-448a-a280-ea09f2a6693f"), Amount = 500, CardNumber = "6104570268579001" }
                    );
                });

            modelBuilder.Entity("AtmMachine.Entities.ProfileDetails", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Name");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("ProfileId");

                    b.ToTable("ProfileDetails");

                    b.HasData(
                        new { ProfileId = new Guid("fa86431a-4029-4942-afab-daf566d2818e"), Address = "Olav M.Troviks Vei 48, H0108", Name = "Alireza Shoaei", PhoneNumber = "48686475" }
                    );
                });

            modelBuilder.Entity("AtmMachine.Entities.UserDetails", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PinCode");

                    b.Property<Guid>("ProfileId");

                    b.HasKey("UserId");

                    b.ToTable("UserDetails");

                    b.HasData(
                        new { UserId = new Guid("cfc64e1f-65b7-448a-a280-ea09f2a6693f"), PinCode = 4060, ProfileId = new Guid("fa86431a-4029-4942-afab-daf566d2818e") }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
